name: Deploy Vue + p5.js to GitHub Pages

on:
  push:
    branches:
      - main  # Change if your branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Change to h3 directory
        run: cd h1

      - name: Install dependencies
        run: |
          cd h1
          npm install

      - name: Build project
        run: |
          cd h1
          npm run build

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: h1/dist  # Adjust the path if needed
